version: '3'

services:
  mssql-service-dev:
    container_name: db-mssql-dev
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04
    ports:
      - "1433:1433"
    volumes:
      - /var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SApass123
      - MSSQL_PID=Developer

  mssql-service-qa:
    container_name: db-mssql-qa
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04
    ports:
      - "1443:1433"
    volumes:
      - /var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=saPASS321
      - MSSQL_PID=Developer
  
    postgres-service:
      image: postgres:10.5
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql