version: '3'

# CREDENTIALS IN THIS FILE ARE MEANT FOR DEV/EXAMPLE ONLY

services:
  cli:
    build: .
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - "$PWD/packages:/opt/packages"
    environment:
      - LOCAL_MSSQL_SERVER=mssql-dev:1433
      - LOCAL_MSSQL_DBNAME=tempdb
      - LOCAL_MSSQL_USERNAME=sa
      - LOCAL_MSSQL_PASSWORD=SApass123
      - QA_MSSQL_SERVER=mssql-dev:1443
      - QA_MSSQL_DBNAME=tempdb
      - QA_MSSQL_USERNAME=sa
      - QA_MSSQL_PASSWORD=saPASS321
    
  mssql-dev:
    container_name: db-mssql-dev
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04
    ports:
      - "1433:1433"
    volumes:
      - /var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SApass123
      - MSSQL_PID=Developer

  mssql-qa:
    container_name: db-mssql-qa
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04
    ports:
      - "1443:1433"
    volumes:
      - /var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=saPASS321
      - MSSQL_PID=Developer
  
  #   postgres-service:
  #     image: postgres:10.5
  #     restart: always
  #     environment:
  #       - POSTGRES_USER=postgres
  #       - POSTGRES_PASSWORD=postgres
  #     logging:
  #       options:
  #         max-size: 10m
  #         max-file: "3"
  #     ports:
  #       - '5432:5432'
  #     volumes: 
  #       - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql